CREATE TABLE NEWBOARD (USERNAME VARCHAR(20) NOT NULL, ADDRESS VARCHAR(200) NOT NULL, STATES VARCHAR(20) NOT
NULL, COUNTRY VARCHAR(20) NOT NULL, ZIPCODE VARCHAR(10), EMAIL VARCHAR(50) NOT NULL, LOSTDATE DATE NOT NULL,
TIM TIME(8), ITEM VARCHAR(50) NOT NULL, CATEGORY INTEGER, DETAILS VARCHAR(500), LOSTADDRESS VARCHAR(250), PHONE
VARCHAR(20) NOT NULL, REFERID VARCHAR(30) NOT NULL, PRIMARY KEY (USERNAME));
